#!/bin/sh -e

set -x

SOURCE_FILES="python_multipart multipart tests"

uv run ruff format --check --diff $SOURCE_FILES
uv run ruff check $SOURCE_FILES
uv run mypy $SOURCE_FILES
uvx check-sdist
uv lock
